# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.101'

- script: dotnet build --configuration $(buildConfiguration) --version-suffix $(build.buildNumber) /warnaserror
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish web'
  inputs:
    command: publish
    projects: '**/FhirDashboard.csproj'
    arguments: '--output $(build.artifactStagingDirectory)/dashboard --configuration $(buildConfiguration) --no-build'
    publishWebProjects: false

- task: PublishBuildArtifacts@1
  displayName: 'publish Dashboard artifacts'
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/dashboard'
    artifactName: 'deploy'
    artifactType: 'container'

- task: PublishBuildArtifacts@1
  displayName: 'publish samples'
  inputs:
    pathToPublish: './deploy/'
    artifactName: 'deploy'
    artifactType: 'container'