# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

variables:
  buildConfiguration: 'Release'
stages:
- stage: Build
  jobs:
    - job: BuildAndPublish
      pool:
         vmImage: 'vs2017-win2016'
      steps:
       - task: DotNetCoreInstaller@0
         inputs:
           version: '2.2.101'
       - script: dotnet build --configuration $(buildConfiguration) --version-suffix $(build.buildNumber) /warnaserror
         displayName: 'dotnet build $(buildConfiguration)'
       - task: DotNetCoreCLI@2
         displayName: 'dotnet publish Integration Tests'
         inputs:
           command: publish
           projects: 'test/**/*.csproj'
           arguments: '--version-suffix $(build.buildnumber) -o "$(build.binariesdirectory)/IntegrationTests" --configuration $(buildConfiguration) --no-build'
           publishWebProjects: false
           zipAfterPublish: false
       - task: PublishBuildArtifacts@1
         displayName: 'publish samples'
         inputs:
           pathToPublish: './deploy/'
           artifactName: 'deploy'
           artifactType: 'container'
       - task: PublishBuildArtifacts@1
         displayName: 'publish Integration Tests'
         inputs:
           pathToPublish: '$(build.binariesdirectory)/IntegrationTests'
           artifactName: 'IntegrationTests'
           artifactType: 'container'
- stage: Deploy
  jobs:
    - job: DeployAndTest
      pool:
        vmImage: 'vs2017-win2016'
      steps:
      - task: DotNetCoreInstaller@0
        displayName: 'Use .NET Core sdk 2.2'
        inputs:
          version: 2.2.101
      - powershell: |
          Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
          Install-Module -Name AzureAD -Force -Verbose -Scope CurrentUser
        displayName: 'Install AzureAD'